### ISSUE TITLE
两个串口同时读取数据，读到的数据会混杂在一起，请问这个应该怎么解决呢？

### ISSUE THREAD

**Issue by AbrahamCaiJin** [seeways/SerialPortAssiatant#1]
两个串口同时读取数据，读到的数据会混杂在一起，请问这个应该怎么解决呢？

**Comment by seeways** [comment]
每个串口使用独立的线程即可解决

**Comment by seeways** [comment]
new SerialPortUtils(串口2, flag2, 波特率, 接收方法);
serialPort1 = new SerialPortUtils(SerialPortConstant.SerialPortPath_ttyS1, SerialPortConstant.SERIAL_PORT_FLAG1, SerialPortConstant.baudrate, new SerialPortCommunicate()); //初始化串口1
        serialPort2 = new SerialPortUtils(SerialPortConstant.SerialPortPath_ttyS4, SerialPortConstant.SERIAL_PORT_FLAG2, SerialPortConstant.baudrate, new SerialPortCommunicate()); //初始化串口2
